import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/Header";
import { AppProvider } from "./component/AppContext";
import ProviderWrapper from "../app/providerWrapper";
import { Toaster } from "react-hot-toast";
import { Open_Sans } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "900"]
});
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body
        className={openSans.className}
        style={{
          overflowX: 'hidden'
        }}
       
      >
        <AppProvider> 
          <main className="w-fill mx-auto p-4">
        <Toaster />
          <Header />
          {children}
          <footer className="text-center mt-10 py-8 border-t border-gray-200 border-solid">
            <p className="text-gray-600 text-md text-center">&copy; 2022 Food Ordering App. All rights reserved.</p>
          </footer>

        </main>
        </AppProvider>
      </body>
    </html>
  );
}
