import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/Header";
import { AppProvider } from "./component/AppContext";
import ProviderWrapper from "../app/providerWrapper";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "900"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={roboto.className}
      >
        <AppProvider> 
          <main className="max-w-4xl mx-auto p-4">
        <Toaster/>
          <Header />
          {children}
          <footer className="text-center mt-10 py-8 border-t border-gray-200 border-solid">
            <p className="text-gray-600 text-md text-center">&copy; 2022 Food Ordering App. All rights reserved.</p>
          </footer>

        </main>
        </AppProvider>
      </body>
    </html>
  );
}
